### ISSUE TITLE
Windows :)

### ISSUE THREAD

**Issue by bofm** [ajdavis/mongo-mockup-db#1]
``` python
# (35x64) C:\dev\mongo>python
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mockupdb
>>> mockupdb.__version__
'1.0.3'
>>> s = mockupdb.MockupDB()
>>> s.run()
65297
>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\Python35x64\Lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "c:\Python35x64\Lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\svustin\Envs\35x64\lib\site-packages\mockupdb\__init__.py", line 1438, in _accept_loop
    client, client_addr = self._listening_sock.accept()
  File "c:\Python35x64\Lib\socket.py", line 195, in accept
    fd, addr = self._accept()
BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately


>>>
```

Windows 10 x64

**Comment by srault95** [comment]
+1

Windows 7 - python 3.4.3
