### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by eliocapelati** [ajdavis/mongo-mockup-db#23]
**Python version:**

```
Python 3.6.7 (default, Dec 26 2018, 00:39:58)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
```

**Mac OS Version:**
```
➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
```

I'm facing a error when a tries to use mockupdb as show in the documentation, following the [introduction](https://mockupdb.readthedocs.io/tutorial.html#introduction) docs, in the 3rd step:

```bash
>>> request.replies({'ok': 1, 'maxWireVersion': 6})
True
```

It raises a exception:

```
>>> request.replies({'ok': 1, 'maxWireVersion': 6})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eliocapelati/.pyenv/versions/3.6.7/envs/venv/lib/python3.6/site-packages/mockupdb/__init__.py", line 444, in replies
    self._replies(*args, **kwargs)
  File "/Users/eliocapelati/.pyenv/versions/3.6.7/envs/venv/lib/python3.6/site-packages/mockupdb/__init__.py", line 798, in _replies
    super(Command, self)._replies(reply)
  File "/Users/eliocapelati/.pyenv/versions/3.6.7/envs/venv/lib/python3.6/site-packages/mockupdb/__init__.py", line 544, in _replies
    self._server._log('\t%d\t<-- %r' % (self.client_port, reply_msg))
  File "/Users/eliocapelati/.pyenv/versions/3.6.7/envs/venv/lib/python3.6/site-packages/mockupdb/__init__.py", line 410, in client_port
    address = self._client.getpeername()
OSError: [Errno 9] Bad file descriptor
```

**Comment by ajdavis** [comment]
Thanks for reporting this bug. It happens when you're following the tutorial by typing in commands in the Python shell: if it takes you more than 10 seconds to reply to MongoClient, then the MongoClient gives up and disconnects from the server, and the server throws an OSError. I've fixed the tutorial to show a longer timeout:
```
>>> MongoClient(server.uri, connectTimeoutMS=999999)
```
