### ISSUE TITLE
Tests log OSErrors on Windows

### ISSUE THREAD

**Issue by ajdavis** [ajdavis/mongo-mockup-db#32]
The AppVeyor builds for Python 3 log errors like:
```
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```
... however, the tests pass. I haven't investigated at all, it's probably just an issue in the test cleanup sequence, but it merits further study.

**Comment by arut-grigoryan** [comment]
Hi, Has the problem been resolved? Find in mockupdb\__init__.py in bind_domain_socket function on 1740 line.
`sock = socket.socket(socket.AF_UNIX)`
Does this mean not to use the package for windows?
When I do server.stop(), recieve error:
`OSError: [WinError 10038] An operation was attempted on something that is not a socket`

Windows 10, python 3.8, mockupdb 1.7.0

**Comment by ajdavis** [comment]
To my knowledge the problem has not been resolved.

Do you get a traceback when you see that error? Does your program crash? Or is it written to stderr without a traceback and your program exits normally?

**Comment by arut-grigoryan** [comment]
This is written to stderr with no trace and your program exits normally.

**Comment by ShaneHarvey** [comment]
Here's an example:
```
$ python setup.py test -s tests.test_mockupdb.TestMockupDB.test_default_wire_version
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point
 independent of test runner are encouraged to use tox.
running egg_info
writing mockupdb.egg-info\PKG-INFO
writing dependency_links to mockupdb.egg-info\dependency_links.txt
writing requirements to mockupdb.egg-info\requires.txt
writing top-level names to mockupdb.egg-info\top_level.txt
reading manifest file 'mockupdb.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
writing manifest file 'mockupdb.egg-info\SOURCES.txt'
running build_ext
test_default_wire_version (tests.test_mockupdb.TestMockupDB) ... Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\python\Python36\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\python\Python36\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\cygwin\home\administrator\mongo-mockup-db\mockupdb\__init__.py", line 1647, in _accept_loop
    client, client_addr = self._listening_sock.accept()
  File "C:\python\Python36\Lib\socket.py", line 205, in accept
    fd, addr = self._accept()
OSError: [WinError 10038] An operation was attempted on something that is not a socket

ok

----------------------------------------------------------------------
Ran 1 test in 0.016s

OK
```
