### ISSUE TITLE
OSError: [WinError 10038] An operation was attempted on something that is not a socket

### ISSUE THREAD

**Issue by brianminsk** [ajdavis/mongo-mockup-db#36]
I was psyched to find MockupDB - I am hoping to test that my PyMongo application handles network issues/errors correctly. Thanks for building it!

Anyway, I can't get very far in the tutorial. I opened up the port in Windows Firewall that Mockup.run returned before running the server.

Windows 10 Home version 2004
mockupdb==1.7.0
pymongo==3.10.1

``` shell
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from mockupdb import *
>>> server = MockupDB()
>>> port = server.run()
>>> port
63292
>>> from pymongo import MongoClient
>>> client = MongoClient(server.uri)
>>> request = server.receives()
>>> request.command_name
'ismaster'
>>> request.replies({'ok': 1, 'maxWireVersion': 6})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Python38\lib\site-packages\mockupdb\__init__.py", line 444, in replies
    self._replies(*args, **kwargs)
  File "D:\Python\Python38\lib\site-packages\mockupdb\__init__.py", line 798, in _replies
    super(Command, self)._replies(reply)
  File "D:\Python\Python38\lib\site-packages\mockupdb\__init__.py", line 544, in _replies
    self._server._log('\t%d\t<-- %r' % (self.client_port, reply_msg))
  File "D:\Python\Python38\lib\site-packages\mockupdb\__init__.py", line 410, in client_port
    address = self._client.getpeername()
OSError: [WinError 10038] An operation was attempted on something that is not a socket
>>> 
```

**Comment by ShaneHarvey** [comment]
I think this was fixed in https://github.com/ajdavis/mongo-mockup-db/pull/35. Can you try installing from master?
```
pip install --upgrade https://github.com/ajdavis/mongo-mockup-db/archive/1b50472e3997b523a2712c4b2f659cee59d407d9.zip
```

**Comment by ajdavis** [comment]
@brianminsk if this *does* solve your problem, I'll upload a new release to PyPI. Please let us know, thanks.

**Comment by brianminsk** [comment]
> I think this was fixed in #35. Can you try installing from master?

This install has the same issue. The stack trace is exactly the same, including line numbers.

**Comment by ajdavis** [comment]
Hi Brian, that doesn't seem right at all. If, for example, the call to `self._replies()` is on line 444, that indicates you're still running MockupDB 1.7.0:
```
  File "D:\Python\Python38\lib\site-packages\mockupdb\__init__.py", line 444, in replies
    self._replies(*args, **kwargs)
```
Can you `pip uninstall mockupdb`, ensure it's gone from your site-packages directory, and try again to install directly from GitHub with pip?

**Comment by brianminsk** [comment]
Ah, so sorry - my bad! I installed it in a different shell window and didn't notice it was in a virtual environment...

That said, same problem, different line numbers. 
PyMongo 3.11 rather than 3.10.1

``` shell
Brian@Silver-Swift MINGW64 /d/github/PASI/providers-db (master)
$ python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from mockupdb import *
>>> server = MockupDB()
>>> port = server.run()
>>> port
65528
>>> from pymongo import MongoClient
>>> client = MongoClient(server.uri)
>>> request = server.receives()
>>> request.command_name
'ismaster'
>>> request.replies({'ok': 1, 'maxWireVersion': 6})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Python38\lib\site-packages\mockupdb\__init__.py", line 442, in replies
    self._replies(*args, **kwargs)
  File "D:\Python\Python38\lib\site-packages\mockupdb\__init__.py", line 824, in _replies
    super(Command, self)._replies(reply)
  File "D:\Python\Python38\lib\site-packages\mockupdb\__init__.py", line 542, in _replies
    self._server._log('\t%d\t<-- %r' % (self.client_port, reply_msg))
  File "D:\Python\Python38\lib\site-packages\mockupdb\__init__.py", line 408, in client_port
    address = self._client.getpeername()
OSError: [WinError 10038] An operation was attempted on something that is not a socket
>>> 
```

**Comment by ShaneHarvey** [comment]
> `OSError: [WinError 10038] An operation was attempted on something that is not a socket`

This error happens when the socket is closed on the remote side and the MongoClient will close the socket if the operation times out (20 seconds by default). For example (on macOS):
```
>>> from mockupdb import *
>>> server = MockupDB()
>>> port = server.run()
>>> port
51366
>>> from pymongo import MongoClient
>>> client = MongoClient(server.uri)
>>> request = server.receives()
>>> request.command_name
'ismaster'
>>> request.replies({'ok': 1, 'maxWireVersion': 6})
True
>>> 
>>> request = server.receives()
>>> import time
>>> time.sleep(20)  # Sleep 20 seconds to ensure the MongoClient operation times out.
>>> request.replies({'ok': 1, 'maxWireVersion': 6})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shane/git/mongo-mockup-db/mockupdb/__init__.py", line 442, in replies
    self._replies(*args, **kwargs)
  File "/Users/shane/git/mongo-mockup-db/mockupdb/__init__.py", line 728, in _replies
    super(OpMsg, self)._replies(reply)
  File "/Users/shane/git/mongo-mockup-db/mockupdb/__init__.py", line 542, in _replies
    self._server._log('\t%d\t<-- %r' % (self.client_port, reply_msg))
  File "/Users/shane/git/mongo-mockup-db/mockupdb/__init__.py", line 408, in client_port
    address = self._client.getpeername()
OSError: [Errno 9] Bad file descriptor
``` 

By default the MongoClient's ismaster operation times out after 20 seconds. Are you waiting 20 seconds between creating the client (`client = MongoClient(server.uri)`) and sending the reply `request.replies({'ok': 1, 'maxWireVersion': 6})`?

Instead of responding to each ismaster command manually [I suggest adding an auto responder like this](https://mockupdb.readthedocs.io/reference.html#mockupdb.MockupDB.autoresponds):
```python
>>> from mockupdb import *
>>> server = MockupDB()
>>> port = server.run()
>>> responder = server.autoresponds('ismaster', maxWireVersion=6)
...
```

**Comment by brianminsk** [comment]
I duplicated what Shane did so that is indeed where the error is coming from. 

That said, I was following the tutorial at https://mockupdb.readthedocs.io/tutorial.html, going along fairly slowly because I am learning & thinking about what is going on, with no knowledge of the time out. Perhaps you don't expect folks to interactively follow this tutorial - not sure - but I would guess I am not the only one who does this. (That may come across as peevish - it's not intended.) Well, plus I may be slower than most ...  :)

**Comment by brianminsk** [comment]
I just tried this again, but in a script, and the behavior is different.
``` Python
""" Python script to recreate a MockupDB error re: https://github.com/ajdavis/mongo-mockup-db/issues/36
"""
from pymongo import MongoClient
from mockupdb import *
import time
import pkg_resources

print("Pymongo version: {}".format(pkg_resources.get_distribution("pymongo").version))
print("MockupDB version: {}".format(pkg_resources.get_distribution("mockupdb").version))
server = MockupDB()
port = server.run()
client = MongoClient(server.uri)
request = server.receives()
print("request.replies returns: {}".format(request.replies({'ok': 1, 'maxWireVersion': 6})))
print("starting 2nd server.receives")
request = server.receives()
print("finished 2nd server.receives")
for i in range(20):
    print(i)
    time.sleep(1)
print("starting 2nd request.replies")
print("request.replies returns: {}".format(request.replies({'ok': 1, 'maxWireVersion': 6})))
print("finished 2nd request.replies")
```
Shell output:
``` Shell
$ python mockupdb-error.py 
Pymongo version: 3.11.0
MockupDB version: 1.8.0.dev0
request.replies returns: True
starting 2nd server.receives
Traceback (most recent call last):
  File "D:\python-scratch\scratch-book\venv\lib\site-packages\mockupdb\__init__.py", line 1354, in receives
    request = self._request_q.get(timeout=0.05)
  File "D:\python-scratch\scratch-book\venv\lib\site-packages\mockupdb\__init__.py", line 311, in get
    return Queue.get(self, block, timeout)
  File "D:\Python\Python38\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mockupdb-error.py", line 17, in <module>
    request = server.receives()
  File "D:\python-scratch\scratch-book\venv\lib\site-packages\mockupdb\__init__.py", line 1357, in receives
    raise AssertionError('expected to receive %r, got nothing'
AssertionError: expected to receive Request(), got nothing
```

**Comment by ShaneHarvey** [comment]
Yes the timeout behavior is not intuitive. We should document this quirk. 

The new error `AssertionError: expected to receive Request(), got nothing`  is discussed in brief here: https://mockupdb.readthedocs.io/tutorial.html#wait-for-a-request-impatiently

You can pass a larger `timeout` to [receives()](https://mockupdb.readthedocs.io/reference.html#mockupdb.MockupDB.receives) or a larger `request_timeout` when creating the MockupDB server: https://mockupdb.readthedocs.io/reference.html?highlight=request_timeout#mockupdb.MockupDB

**Comment by brianminsk** [comment]
When I try to send a 2nd command to the server it hangs, never timing out. I've tried a few different commands and they all hang. 

Maybe I am not understanding something?

```python
""" Python script to recreate a MockupDB error re: https://github.com/ajdavis/mongo-mockup-db/issues/36
"""
from pymongo import MongoClient
from mockupdb import *
import time
import pkg_resources


print("Pymongo version: {}".format(pkg_resources.get_distribution("pymongo").version))
print("MockupDB version: {}".format(pkg_resources.get_distribution("mockupdb").version))
server = MockupDB(request_timeout=5)
port = server.run()
client = MongoClient(server.uri)
request = server.receives()
print("request: {}".format(request))
print("request.replies returns: {}".format(request.replies({'ok': 1, 'maxWireVersion': 6})))
# responder = server.autoresponds('ismaster', maxWireVersion=6)
# client.admin.command('ismaster') == {'ok': 1, 'maxWireVersion': 6}
print("client sending ismaster")
client.admin.command('ismaster')  # hangs here
print("starting 2nd server.receives")
request = server.receives(1)
print("request: {}".format(request))
print("finished 2nd server.receives")
for i in range(20):
    print(i)
    time.sleep(1)
print("starting 2nd request.replies")
print("request.replies returns: {}".format(request.replies({'ok': 1, 'maxWireVersion': 6})))
print("finished 2nd request.replies")
```

**Comment by ShaneHarvey** [comment]
Instead of responding to each ismaster command manually I suggest adding an auto responder with [server.autoresponds](https://mockupdb.readthedocs.io/reference.html#mockupdb.MockupDB.autoresponds). Responding to each ismaster command manually requires a detailed knowledge of driver internals. For example, your example hangs because this line blocks waiting for the server to respond. Instead you need to use `going()` like this:
```
client.admin.command('ismaster')  # hangs here
with going(client.admin.command, 'ismaster') as future:
    # Reply to the first isMaster (the connection handshake)
    server.receives().replies({'ok': 1, 'maxWireVersion': 6})
    # Reply to the second isMaster (the actual command)
    server.receives().replies({'ok': 1, 'maxWireVersion': 6})
```
Check out the test suite for more examples: https://github.com/ajdavis/mongo-mockup-db/blob/873e05c/tests/test_mockupdb.py#L366-L367

You may also be interested in https://github.com/ajdavis/pymongo-mockup-tests/ where we use this library to test the correctness of pymongo.

**Comment by brianminsk** [comment]
That example didn't work for me but that's OK because it's instructive enough and not relevant for the testing I want to do - I got onto this path only from going through the tutorial. 

I think I have enough to go on to do the testing I want to do. Thanks for responding! And thanks for pointing me to the pymongo tests - it looks like they will be helpful.

p.s. Here's my script for your example if you want to try. It's raising an exception when `going` exits.
```python
import pkg_resources
from pymongo import MongoClient
from mockupdb import *


print("Pymongo version: {}".format(pkg_resources.get_distribution("pymongo").version))
print("MockupDB version: {}".format(pkg_resources.get_distribution("mockupdb").version))
server = MockupDB(request_timeout=10)
port = server.run()
client = MongoClient(server.uri)
with going(client.admin.command, 'ismaster') as future:
    # Reply to the first isMaster (the connection handshake)
    print("1st receives/replies: {}".format(server.receives().replies({'ok': 1, 'maxWireVersion': 6})))
    # Reply to the second isMaster (the actual command)
    print("2nd receives/replies: {}".format(server.receives().replies({'ok': 1, 'maxWireVersion': 6})))

print("going context mgr finished")

response = future()
print("response: {}".format(response))
```

**Comment by ShaneHarvey** [comment]
Your example needs a slight change in order to work. This works:
```python
import pkg_resources
from pymongo import MongoClient
from mockupdb import *


print("Pymongo version: {}".format(pkg_resources.get_distribution("pymongo").version))
print("MockupDB version: {}".format(pkg_resources.get_distribution("mockupdb").version))
server = MockupDB(request_timeout=10)
port = server.run()
client = MongoClient(server.uri)
print("1st receives/replies: {}".format(server.receives().replies({'ok': 1, 'maxWireVersion': 6})))
with going(client.admin.command, 'ismaster') as future:
    # Reply to the first isMaster (the connection handshake)
    print("2nd receives/replies: {}".format(server.receives().replies({'ok': 1, 'maxWireVersion': 6})))
    # Reply to the second isMaster (the actual command)
    print("3rd receives/replies: {}".format(server.receives().replies({'ok': 1, 'maxWireVersion': 6})))

print("going context mgr finished")

response = future()
print("response: {}".format(response))
```
Output:
```
$ python issue36.py
Pymongo version: 3.11.0
MockupDB version: 1.8.0.dev0
1st receives/replies: True
2nd receives/replies: True
3rd receives/replies: True
going context mgr finished
response: {'ok': 1, 'maxWireVersion': 6}
```

**Comment by brianminsk** [comment]
Ah, I see - 'ismaster' is sent every time the client connects to the server. Thus the need for the auto responder.

Thanks.
