### ISSUE TITLE
When you project a query things seem to break

### ISSUE THREAD

**Issue by wilsonge** [ajdavis/mongo-mockup-db#7]
I got the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mockupdb/__init__.py", line 1035, in wrapper
    return meth(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mockupdb/__init__.py", line 1480, in _server_loop
    request = mock_server_receive_request(client, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mockupdb/__init__.py", line 1580, in mock_server_receive_request
    return OPCODES[opcode].unpack(msg_bytes, client, server, request_id)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mockupdb/__init__.py", line 553, in unpack
    assert len(docs) == 1
AssertionError
```

I got this when calling a query 

```
        variable = self.collection.find_one({'_id': ObjectId(<id_name>)}, {'some_var': 1})
```

Debugging the variable doc gave me

```
<class 'list'>: [OrderedDict([('find', '<collection_name>'), ('filter', OrderedDict([('_id', ObjectId('<id_name>'))])), ('projection', OrderedDict([('<some_var>', 1)])), ('limit', 1), ('singleBatch', True)]), OrderedDict([('modes', 1)])]
```

so i'm assuming something about projecting is causing issues. My PyMongo client version is 3.5.1

**Comment by ajdavis** [comment]
Thanks for the report. This has actually revealed a minor bug in PyMongo's implementation of the "find" command ever since PyMongo 3.2:

https://jira.mongodb.org/browse/PYTHON-1479

**Comment by ajdavis** [comment]
Closing; this is a PyMongo bug, not a MockupDB bug.
